server:
  port: 8086

spring:
  application:
    name: alert-service
  datasource:
    url: jdbc:mysql://localhost:3306/navy_alert_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: alert_group
    streams:
      application-id: alert_service_streams
      bootstrap-servers: localhost:9092
application:
  security:
    jwt:
      secret-key: kjZkiL/+bIpdAeYYYrMQCRh0yb+09i/hK23P91sQRBI=
      expiration: 86400000 # 1 day in milliseconds      

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
