server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/navy_mission_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
